# Generated by Django 5.0.6 on 2024-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(default=list),
        ),
    ]
