# Generated by Django 5.0.6 on 2024-06-14 20:43

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount_alter_product_available_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(default=list, validators=[products.validators.ProductSizeValidator.validate_size]),
        ),
    ]
